// Author: Ian D. Hanley (DevSecOpsDad) | linkedin.com/in/ianhanley | devsecopsdad.com | devsecopsdadattack.com
// Determine the distribution of query types
// Source: Watching The DNS Watcher: Pihole Logs In Sentinel (2025-03-30) — https://www.hanley.cloud/2025-03-30-Watching-the-DNS-Watcher-Pihole-Logs-in-Sentinel/
// Platforms: Pi-hole
// Data: pihole_CL

PiHole
| summarize Count = count() by QueryType  // Aggregate counts by query type
| render piechart  // Visualize the data as a pie chart

